# Generated by Django 5.0.14 on 2026-07-29 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0008_alter_sshkey_unique_together_sshkey_owner_and_more"),
        ("playbooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbookrepository",
            name="api_key_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="playbookrepository",
            name="ssh_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playbook_repositories",
                to="builds.sshkey",
            ),
        ),
    ]
