# Generated by Django 5.0.14 on 2026-08-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afterburners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="afterburneritem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("hostname", "Hostname"),
                    ("local_user", "Local user"),
                    ("ad_join", "AD join"),
                    ("static_ip", "Static IP"),
                    ("luks_rotate", "Set LUKS password"),
                    ("wait_for_enter", "Wait for Enter"),
                    ("custom_script", "Custom script"),
                ],
                max_length=32,
            ),
        ),
    ]
