# Generated by Django 5.0.14 on 2026-08-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afterburners", "0003_alter_afterburneritem_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="afterburneritem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("hostname", "Hostname"),
                    ("local_user", "Local user"),
                    ("ad_join", "AD join"),
                    ("static_ip", "Static IP"),
                    ("luks_rotate", "Set LUKS password"),
                    ("bootloader_password", "Set Bootloader password"),
                    ("tpm_integration", "TPM integration"),
                    ("wait_for_enter", "Wait for Enter"),
                    ("custom_script", "Custom script"),
                ],
                max_length=32,
            ),
        ),
    ]
