# Generated by Django 5.0.14 on 2026-07-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("layouts", "0001_initial"),
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[("pxe", "PXE bundle"), ("usb", "USB image")],
                        max_length=8,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("sha256", models.CharField(max_length=64)),
                ("compressed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuildMachineConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("cpu", models.PositiveIntegerField(default=4)),
                ("memory_mib", models.PositiveIntegerField(default=8192)),
                ("disk_gib", models.PositiveIntegerField(default=80)),
                (
                    "boot_mode",
                    models.CharField(
                        choices=[
                            ("uefi", "UEFI"),
                            ("bios", "BIOS"),
                            ("both", "BIOS + UEFI"),
                        ],
                        default="both",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BuildDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("playbook_repo", models.CharField(blank=True, max_length=255)),
                ("playbook_branch", models.CharField(default="main", max_length=120)),
                ("playbook_path", models.CharField(blank=True, max_length=255)),
                ("output_pxe", models.BooleanField(default=True)),
                ("output_usb_img", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("failed", "Failed"),
                            ("succeeded", "Succeeded"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "iso_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.isoimage",
                    ),
                ),
                (
                    "operating_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.operatingsystem",
                    ),
                ),
                (
                    "package_lists",
                    models.ManyToManyField(blank=True, to="packages.packagelist"),
                ),
                (
                    "partition_layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="layouts.partitionlayout",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
