# Generated by Django 5.0.14 on 2026-07-27 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("builds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="builddefinition",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buildartifact",
            name="build",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="builds.builddefinition",
            ),
        ),
        migrations.AddField(
            model_name="builddefinition",
            name="machine_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="builds.buildmachineconfig",
            ),
        ),
    ]
