# Generated by Django 5.0.14 on 2026-07-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildmachineconfig",
            name="hypervisor_uri",
            field=models.CharField(default="qemu:///system", max_length=200),
        ),
        migrations.AddField(
            model_name="buildmachineconfig",
            name="kickstart_timeout_minutes",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="buildmachineconfig",
            name="libvirt_network",
            field=models.CharField(default="default", max_length=120),
        ),
    ]
