# Generated by Django 5.0.14 on 2026-07-27 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0003_buildmachineconfig_hypervisor_uri_and_more"),
        ("playbooks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildPlaybookSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook_selections",
                        to="builds.builddefinition",
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_selections",
                        to="playbooks.playbook",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("build", "order"), ("build", "playbook")},
            },
        ),
        migrations.AddField(
            model_name="builddefinition",
            name="playbooks",
            field=models.ManyToManyField(
                blank=True,
                related_name="build_definitions",
                through="builds.BuildPlaybookSelection",
                to="playbooks.playbook",
            ),
        ),
    ]
