# Generated by Django 5.0.14 on 2026-07-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0005_normalize_buildmachineconfig_network"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildmachineconfig",
            name="libvirt_network",
            field=models.CharField(default="wsbuildnet", max_length=120),
        ),
    ]
