# Generated by Django 5.0.14 on 2026-07-29 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0007_sshkey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sshkey",
            unique_together={("build", "name")},
        ),
        migrations.AddField(
            model_name="sshkey",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ssh_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sshkey",
            name="scope",
            field=models.CharField(
                choices=[
                    ("builder", "Builder"),
                    ("image_build", "Image Build"),
                    ("user", "User"),
                ],
                default="builder",
                max_length=16,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sshkey",
            unique_together={("build", "name"), ("owner", "scope", "name")},
        ),
    ]
