# Generated by Django 5.0.14 on 2026-08-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0014_alter_builddefinition_current_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildartifact",
            name="release_group",
            field=models.CharField(blank=True, default="default", max_length=64),
        ),
        migrations.AddField(
            model_name="buildartifact",
            name="release_label",
            field=models.CharField(blank=True, default="latest", max_length=64),
        ),
        migrations.AlterField(
            model_name="builddefinition",
            name="current_step",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("vm_shell", "Create VM"),
                    ("install_os", "Install OS"),
                    ("run_playbooks", "Run Playbooks"),
                    ("shutdown", "Shutdown"),
                    ("dump_partitions", "Dump Partitions"),
                    ("save_release", "Save Release"),
                    ("cleanup", "Cleanup"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
