# Generated by Django 5.0.14 on 2026-08-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0016_buildafterburnerselection_builddefinition_afterburners"),
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildRepositorySelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("enable_during_build", models.BooleanField(default=False)),
                ("enable_before_afterburner", models.BooleanField(default=False)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_selections",
                        to="builds.builddefinition",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_selections",
                        to="repositories.packagerepository",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("build", "order"), ("build", "repository")},
            },
        ),
    ]
