# Generated by Django 5.0.14 on 2026-08-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0017_buildrepositoryselection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builddefinition",
            name="current_step",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("vm_shell", "Create VM"),
                    ("install_os", "Install OS"),
                    ("install_packages", "Install Packages"),
                    ("run_playbooks", "Run Playbooks"),
                    ("shutdown", "Shutdown"),
                    ("dump_partitions", "Dump Partitions"),
                    ("save_release", "Save Release"),
                    ("cleanup", "Cleanup"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
