# Generated by Django 5.0.14 on 2026-08-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0018_alter_builddefinition_current_step"),
        ("repositories", "0002_redhatrepositorycatalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="builddefinition",
            name="rhsm_activation_key_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="builddefinition",
            name="rhsm_auth_mode",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("userpass", "Red Hat username/password"),
                    ("activation_key", "Activation key + org ID"),
                ],
                default="none",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="builddefinition",
            name="rhsm_org_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="builddefinition",
            name="rhsm_password_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="builddefinition",
            name="rhsm_repositories",
            field=models.ManyToManyField(
                blank=True, to="repositories.redhatrepositorycatalog"
            ),
        ),
        migrations.AddField(
            model_name="builddefinition",
            name="rhsm_username",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
