# Generated by Django 5.0.14 on 2026-08-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0019_builddefinition_rhsm_activation_key_encrypted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builddefinition",
            name="rhsm_auth_mode",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("config_credentials", "Use configuration credentials"),
                    ("userpass", "Red Hat username/password"),
                    ("activation_key", "Activation key + org ID"),
                ],
                default="none",
                max_length=24,
            ),
        ),
    ]
