# Generated by Django 5.0.14 on 2026-07-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serverconfig", "0003_rename_deployer_fields_to_builder_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuilderProgressEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("start", "Start"),
                            ("progress", "Progress"),
                            ("iso", "ISO"),
                            ("cleanup", "Cleanup"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="progress",
                        max_length=32,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
