# Generated by Django 5.0.14 on 2026-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serverconfig", "0004_builderprogressevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverconfiguration",
            name="use_redhat_subscription",
            field=models.BooleanField(default=True),
        ),
    ]
