# Generated by Django 5.0.14 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serverconfig", "0005_serverconfiguration_use_redhat_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverconfiguration",
            name="rhn_password_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="serverconfiguration",
            name="rhn_username",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
