# Generated by Django 5.0.14 on 2026-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PackageRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "family",
                    models.CharField(
                        choices=[("deb", "Debian / Ubuntu"), ("rpm", "RHEL / Fedora")],
                        max_length=8,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("base_url", models.CharField(max_length=500)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("basic", "Username + password"),
                            ("token", "Token"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=120)),
                ("secret_encrypted", models.TextField(blank=True)),
                (
                    "signing_mode",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("url", "GPG key URL"),
                            ("inline", "Inline GPG key"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("gpg_key_url", models.CharField(blank=True, max_length=500)),
                ("gpg_key_inline", models.TextField(blank=True)),
                ("deb_suite", models.CharField(blank=True, max_length=120)),
                ("deb_components", models.CharField(blank=True, max_length=255)),
                ("rpm_repoid", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
