# Generated by Django 5.0.14 on 2026-08-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedHatRepositoryCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rhel_major", models.PositiveIntegerField()),
                ("architecture", models.CharField(default="x86_64", max_length=32)),
                ("repo_id", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=500)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("baseurl", "baseurl"),
                            ("metalink", "metalink"),
                            ("mirrorlist", "mirrorlist"),
                        ],
                        default="baseurl",
                        max_length=16,
                    ),
                ),
                ("source_url", models.CharField(blank=True, max_length=500)),
                ("enabled_by_default", models.BooleanField(default=False)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rhel_major", "repo_id"],
                "unique_together": {("rhel_major", "architecture", "repo_id")},
            },
        ),
    ]
