# Generated by Django 5.0.14 on 2026-07-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartitionLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("yaml_fallback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartitionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=120)),
                ("mount_point", models.CharField(blank=True, max_length=120)),
                ("filesystem", models.CharField(max_length=32)),
                (
                    "size_mode",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed MiB"),
                            ("remainder", "Use remainder"),
                        ],
                        default="fixed",
                        max_length=16,
                    ),
                ),
                ("size_mib", models.PositiveIntegerField(blank=True, null=True)),
                ("gpt_type", models.CharField(blank=True, max_length=64)),
                ("is_boot", models.BooleanField(default=False)),
                ("luks_enabled", models.BooleanField(default=False)),
                ("luks_name", models.CharField(blank=True, max_length=64)),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="layouts.partitionlayout",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("layout", "order")},
            },
        ),
    ]
