# Generated by Django 5.0.14 on 2026-07-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperatingSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("rhel", "RHEL/Fedora family"),
                            ("debian", "Debian/Ubuntu family"),
                        ],
                        default="rhel",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "family")},
            },
        ),
        migrations.CreateModel(
            name="ISOImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=64)),
                ("iso_file", models.FileField(upload_to="isos/")),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operating_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isos",
                        to="catalog.operatingsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["operating_system__name", "version"],
                "unique_together": {("operating_system", "version")},
            },
        ),
        migrations.CreateModel(
            name="ISOVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("value", models.TextField()),
                (
                    "iso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="catalog.isoimage",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "unique_together": {("iso", "key")},
            },
        ),
        migrations.CreateModel(
            name="OSVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("value", models.TextField()),
                (
                    "operating_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="catalog.operatingsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "unique_together": {("operating_system", "key")},
            },
        ),
    ]
